### ISSUE TITLE
No Config Files Created

### ISSUE THREAD

**Issue by NateyBoyDM** [vaxerski/Hyprland#22] opened 2022-04-11 23:41 UTC
**Describe the bug**
No files for hypr or hyprland are found in .config. I've tried this on a bare metal EndeavourOS, VM EndeavourOS, as well as VM Garuda Linux. 

**Images/videos/anything that would help**

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
sWLRBackend was NULL!

**Comment by vaxerski** [comment] 2022-04-12 04:39
well, no config files are created because Hyprland doesn't start as the backends could not be created. 

Start Hyprland from a TTY and see the output. WLR should print a bunch of errors that tell you what's wrong. Post them here.

**Comment by ThatOneCalculator** [comment] 2022-04-13 19:04
This can be resolved with `make config` now, yea?

**Comment by vaxerski** [comment] 2022-04-13 19:11
`make config` configures the repository for compiling, no.

**Comment by ThatOneCalculator** [comment] 2022-04-13 19:15
Ah mb

**Comment by vaxerski** [comment] 2022-04-18 19:51
closing due to inactivity

**Comment by YaoReTian** [comment] 2022-04-18 19:51
try cloning the repo and copying the config file `/example/hyprland.conf` into `~/.config/hypr/`

**Closed by vaxerski** 2022-04-18 19:51 UTC
Labels: bug

**Comment by vaxerski** [comment] 2022-04-18 19:52
misleading title, the issue is crash on start with the backend not initializing.
