### ISSUE TITLE
Gtk4 windows dont render correctly

### ISSUE THREAD

**Issue by godalming123** [vaxerski/Hyprland#137] opened 2022-05-31 16:10 UTC
**Describe the bug**

When you open a gtk4 window the resize touch targets are giant

**Images/videos/anything that would help**

gnome screenshot does'nt appear to work will see if I can get a screnshot later.

**logfile**
```14335 [LOG] Keybind triggered, calling dispatcher (64, 65293)
14336 [LOG] Executing WAYLAND_DISPLAY=wayland-0 DISPLAY=:0 alacritty
14337 [LOG] New XDG Surface created. (0x0 at 0 0)
14338 [LOG] Registered signal for owner 5cf20890: 5ceed978 -> 5cf208f8 (owner: XDG Window)
14339 [LOG] Registered signal for owner 5cf20890: 5ceed988 -> 5cf20960 (owner: XDG Window)
14340 [LOG] Registered signal for owner 5cf20890: 5ceed948 -> 5cf209c8 (owner: XDG Window)
14341 [LOG] OPENINGON: 5cf003e0, Workspace: 1, Monitor: 1
14342 [LOG] Set keyboard focus to surface 5cf1c5d0, with window name: Alacritty
14343 [LOG] Registered signal for owner 5cf29590: 5cf1c8a0 -> 5cf29598 (owner: SurfaceTreeNode)
14344 [LOG] Registered signal for owner 5cf29590: 5cf1c890 -> 5cf29600 (owner: SurfaceTreeNode)
14345 [LOG] Registered signal for owner 5cf29590: 5cf1c8b0 -> 5cf29668 (owner: SurfaceTreeNode)
14346 [LOG] Window got assigned a surfaceTreeNode 5cf29590
14347 [LOG] Registered signal for owner 5cf20890: 5cf1c890 -> 5cf20890 (owner: XDG Window Late)
14348 [LOG] Registered signal for owner 5cf20890: 5cdba5f0 -> 5cf20a30 (owner: XDG Window Late)
14349 [LOG] Registered signal for owner 5cf20890: 5cdba590 -> 5cf20a98 (owner: XDG Window Late)
14350 [LOG] Registered signal for owner 5cf20890: 5ceed968 -> 5cf20b00 (owner: XDG Window Late)
14351 [LOG] Map request dispatched, monitor HDMI-A-1, xywh: 7.000000 547.000000 946.000000 526.000000
14352 [LOG] Window 5cf20890 set title to ~
14353 [LOG] Window 5cf20890 set title to gnome-control-center ~
14354 [LOG] New XDG Surface created. (0x0 at 0 0)
14355 [LOG] Registered signal for owner 5cedeba0: 5cf30198 -> 5cedec08 (owner: XDG Window)
14356 [LOG] Registered signal for owner 5cedeba0: 5cf301a8 -> 5cedec70 (owner: XDG Window)
14357 [LOG] Registered signal for owner 5cedeba0: 5cf30168 -> 5cedecd8 (owner: XDG Window)
14358 [LOG] OPENINGON: 5cd26fd0, Workspace: 1, Monitor: 1
14359 [LOG] Set keyboard focus to surface 5cf2d360, with window name: Settings
14360 [LOG] Registered signal for owner 5cf26e30: 5cf2d630 -> 5cf26e38 (owner: SurfaceTreeNode)
14361 [LOG] Registered signal for owner 5cf26e30: 5cf2d620 -> 5cf26ea0 (owner: SurfaceTreeNode)
14362 [LOG] Registered signal for owner 5cf26e30: 5cf2d640 -> 5cf26f08 (owner: SurfaceTreeNode)
14363 [LOG] Window got assigned a surfaceTreeNode 5cf26e30
14364 [LOG] Registered signal for owner 5cedeba0: 5cf2d620 -> 5cedeba0 (owner: XDG Window Late)
14365 [LOG] Registered signal for owner 5cedeba0: 5cdec980 -> 5ceded40 (owner: XDG Window Late)
14366 [LOG] Registered signal for owner 5cedeba0: 5cdec920 -> 5cededa8 (owner: XDG Window Late)
14367 [LOG] Registered signal for owner 5cedeba0: 5cf30188 -> 5cedee10 (owner: XDG Window Late)
14368 [LOG] Map request dispatched, monitor HDMI-A-1, xywh: 7.000000 547.000000 466.000000 526.000000
14369 [LOG] Set keyboard focus to surface 5cf1c5d0, with window name: gnome-control-center ~
14370 [LOG] Set keyboard focus to surface 5cee1a40, with window name: vim /tmp/hypr/hyprla ~
```

This is the a snippet from my log file, ending with me set the focus to my vim window and copying the logs and starting a while before that. I used gnome settings to record this but the eww gtk4 debug menu also fails with the same glitches. I can attach the logfile for that if necersarry

**Comment by vaxerski** [comment] 2022-05-31 16:12
duplicate of #117 also read the FAQ entry about GTK
![image](https://user-images.githubusercontent.com/43317083/171220484-893ed418-eac5-4a8a-990f-ccceff3dabdd.png)

About screenshots, read the FAQ:
![image](https://user-images.githubusercontent.com/43317083/171220650-44668e82-e17c-4874-9fc5-6f1f3c209b59.png)

**Comment by fufexan** [comment] 2022-05-31 16:12
![image](https://user-images.githubusercontent.com/36706276/171220524-f8a50638-024f-4bc8-9e94-9cae8c59d72b.png)
EasyEffects is using GTK4, and I see the problem you describe.

**Closed** 2022-05-31 16:12 UTC
Labels: bug

**Comment by vaxerski** [comment] 2022-05-31 16:16
most likely this
![image](https://user-images.githubusercontent.com/43317083/171222176-cc9ccc43-b419-4d9e-80ef-018cd54c14ff.png)

**Comment by fufexan** [comment] 2022-05-31 16:30
@vaxerski did that, behaves the same. Also I have the `gtk-4.0/gtk.css` set and it does the same.

**Comment by vaxerski** [comment] 2022-05-31 16:31
launch it from the terminal and see what errors are printed. Doesn't help that I've been using EasyEffects for ages now and all is well.

**Comment by fufexan** [comment] 2022-05-31 16:35
Weird... starting from terminal it all works well, no errors printed. Starting with wofi makes it misbehave. Checked the .desktop file, `Exec=easyeffects`. Thought some flags might be wonky. So I'm not sure what's causing it.
