### ISSUE TITLE
Crashes whenever an application starts

### ISSUE THREAD

**Issue by ERROR-404-NULL-NOT-FOUND** [vaxerski/Hyprland#74] opened 2022-05-15 15:53 UTC
**Describe the bug**
Whenever an appliaction starts, Hyprland does the animation, and then immediately crashes

**Images/videos/anything that would help**

https://user-images.githubusercontent.com/76877633/168481832-916bf523-c247-42f6-9fc8-c9b0053a4f17.MOV

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>)
[hyprland.log](https://github.com/vaxerski/Hyprland/files/8695325/hyprland.log)
[coredump.log](https://github.com/vaxerski/Hyprland/files/8695326/coredump.log)

**Comment by vaxerski** [comment] 2022-05-15 16:14
Compile in debug and send the coredump from debug, please. I can see you're using a packaged version, too (probably AUR?), have you tried compiling from source?

**Comment by ThatOneCalculator** [comment] 2022-05-15 17:18
> Compile in debug and send the coredump from debug, please. I can see you're using a packaged version, too (probably AUR?), have you tried compiling from source?

I can reproduce this too, actually. Happens both from source and from AUR (although now the AUR has complete parity with source)

**Comment by vaxerski** [comment] 2022-05-15 17:52
I can't though, someone send me a coredump plox

**Comment by ThatOneCalculator** [comment] 2022-05-15 18:07
Actually seemed to be a wlroots issue, forcing an upgrade on `wlroots-git` fixed it :D

**Comment by vaxerski** [comment] 2022-05-15 18:08
@ERROR-404-NULL-NOT-FOUND update wlr

**Comment by ThatOneCalculator** [comment] 2022-05-15 18:52
@vaxerski Actually seems to be something slightly diff, tried to install again and it immediately crashes, even without opening an application.

https://zer0b.in/p96WU6Fg

**Comment by vaxerski** [comment] 2022-05-15 19:05
again, build in debug.

**Comment by ThatOneCalculator** [comment] 2022-05-15 19:17
Actually I built from the offline PKGBUILD (not directly from AUR). Debug build works fine. Seems to be an issue only with `make release`.

**Comment by vaxerski** [comment] 2022-05-15 19:18
well i can disprove that by saying works for me

give the coredump from `make release` then and NOT the pkgbuild, so the symbols aren't stripped for god's sake

**Comment by ThatOneCalculator** [comment] 2022-05-15 19:19
Actually `make release` on its own is working fine too so something's really weird when making it from the PKGBUILD. Debugging now.

**Comment by vaxerski** [comment] 2022-05-15 19:23
MAGIC.

Try what made Hypr work. It was some idiotic buildflags iirc. See hypr's pkgbuild, they made it work.

**Comment by ThatOneCalculator** [comment] 2022-05-15 19:25
Ok, turns out the old `package()` function was broken, fixed it and pushed a new ver. Should be fixed.

**Comment by vaxerski** [comment] 2022-05-15 19:27
T1C at 6:46PM: Imagine blaming my amazing AUR pkgbuild smh

T1C at 9:25PM: 

:trollface:

**Comment by ThatOneCalculator** [comment] 2022-05-15 19:55
# :trollface:

**Comment by ThatOneCalculator** [comment] 2022-05-15 21:01
@ERROR-404-NULL-NOT-FOUND This issue should now be completely fixed.
@vaxerski I believe this issue can now be closed.

**Comment by vaxerski** [comment] 2022-05-15 21:09
ok

**Closed by vaxerski** 2022-05-15 21:09 UTC
Labels: bug
