### ISSUE TITLE
Crash without systemd and elogind

### ISSUE THREAD

**Issue by linux-leo** [vaxerski/Hyprland#123] opened 2022-05-29 18:39 UTC
**Describe the bug**

I am running Obarun Linux (no systemd, but s6) in a vm, set the XDG Runtime Enviroment to /tmp/${UID} and configured the libseat libary to use seatd.

After all of that Hyprland just crashes on startup, I'm on the latest version because I retested after running Paru -Syu.

**Images/videos/anything that would help**

![Screenshot_obarun_2022-05-29_20:08:11](https://user-images.githubusercontent.com/63003858/170886353-7ad40647-becd-4b42-b0fe-7c994cfb2c1f.png)

Please attach a log (it's in /tmp/hypr/hyprland.log) and, if crashing, a crashdump (coredumpctl, then coredumpctl info <pid>):

S6 has no built in functionality for crashdumps and i didn't know how to get the log out of the VM, but it is on the screenshot.

**Comment by vaxerski** [comment] 2022-05-29 19:23
literally no clue, and without a coredump I can't do much.

Please consider using a normal human being distro if you can't get a coredump on s6.

Furthermore, you should NOT have to set the XDG vars manually, that simply hints at you using a DIY distro without the required knowledge to use a DIY distro.

Can't reproduce.

**Comment by linux-leo** [comment] 2022-05-29 19:45
Im not even sure if it crashed, there's no core dumped message, just the error code 139.
I'm setting the XDG var with a custom startup script to /tmp/${UID} because elogind is the only package that does it by default and its not installed.

**Comment by vaxerski** [comment] 2022-05-29 19:49
no clue. Please reproduce on a normal human distro, otherwise this won't be fixed.

**Comment by ThatOneCalculator** [comment] 2022-05-29 20:33
I wouldnt really say there's a "human distro", something like Artix can use s6 and be as user-friendly as Arch.

**Comment by vaxerski** [comment] 2022-05-29 20:36
option a) give me a coredump
option b) give me a coredump

I don't care whether you use systemd or not, I can't reproduce and I don't have a coredump.

**Comment by ThatOneCalculator** [comment] 2022-05-29 20:41
@linux-leo https://wiki.archlinux.org/title/Core_dump#Using_ulimit

**Comment by linux-leo** [comment] 2022-05-29 20:51
So i enabled coredumps and uninstalled the AUR version (vaxerski said he doesn't want coredumps from the AUR version in another Issue), but its late where I live so I will try tomorrow.

**Comment by linux-leo** [comment] 2022-05-30 12:12
So i got a coredump but still need to figure out how i can get it out of the vm

**Comment by linux-leo** [comment] 2022-05-30 12:50
Ok i finally have the coredump, where should i upload it?. Its 126 Mib.

**Comment by vaxerski** [comment] 2022-05-30 12:53
if you cant upload it, debug it with gdb and give the output of `bt -full`. Screenshot the backtrace.

**Comment by linux-leo** [comment] 2022-05-30 12:55
[core.1103.tar.gz](https://github.com/vaxerski/Hyprland/files/8798442/core.1103.tar.gz)

Here it is. Just needed to compress it first

**Comment by vaxerski** [comment] 2022-05-30 15:17
![image](https://user-images.githubusercontent.com/43317083/171021436-24e67136-10a7-458e-bb65-10e1e4e06bd0.png)

Not a problem with hyprland, not the latest version or broken coredump.

Please use the latest RELEASE (in the Releases tab) and then provide a full coredump from that version.

**Comment by linux-leo** [comment] 2022-05-30 16:02
I built it from source after installing and uninstalling the AUR version. So it was the latest version. Should I reinstall all dependencies from source too?

If its a broken coredump I can't do anything about that, I followed the Instructions using ulimit and don't have any other way to get coredumps.

**Comment by vaxerski** [comment] 2022-05-30 16:23
use the release in the releases tab. it's compiled.

**Comment by linux-leo** [comment] 2022-05-30 16:48
[core.748.tar.gz](https://github.com/vaxerski/Hyprland/files/8799811/core.748.tar.gz)
Another coredump, this time with the release binary

**Comment by vaxerski** [comment] 2022-05-30 18:54
![image](https://user-images.githubusercontent.com/43317083/171047476-0b0941a3-9df5-4ea5-83f2-fb5cd73b83f5.png)

your mesa drivers are causing issues. Something is clearly wrong with your system. If compiling with LEGACY_RENDERER doesn't help, it's probably either a missing package, misconfiguration, dead peripheral or you launching in a VM without making the VM able to run a wayland compositor.

**Comment by linux-leo** [comment] 2022-05-30 20:20
Will create a fresh vm tomorrow and try to figure this out. But its not a problem with hyprland so feel free to close this.

**Closed** 2022-05-30 20:28 UTC
Labels: bug, can't reproduce
